config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  get "userprofile" => "userprofile#userprofile"
  devise_for :users
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { large: "600x600#", medium: "1000x1000#", thumb: "100x100#" }, default_url: ""
  	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_attached_file :profilephoto, styles: { large: "400x400#", medium: "100x100#", thumb: "30x30#" }, default_url: ""
  validates_attachment_content_type :profilephoto, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_in)        << :name
   devise_parameter_sanitizer.for(:sign_up)        << :name
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:sign_in)        << :profilephoto
   devise_parameter_sanitizer.for(:sign_up)        << :profilephoto
   devise_parameter_sanitizer.for(:account_update) << :profilephoto
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @comment.destroy
    @post=  Post.find(@comment.post_id)
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end

  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:post_id, :body, :user_id, :profilephoto)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destory]

  def index 
    @posts = Post.where(["title LIKE ?","%#{params[:search]}%"])
    @posts = @posts.order("posts.updated_at desc")
    #only recent
    #@posts = @posts.where(["created_at >= ? AND created_at <= ?", Date.today.beginning_of_day, Date.today.end_of_day])
  end

  def show
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
      respond_to do |format|
        format.html {redirect_to :back}
        format.js
      end
  end
  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
    
  end

  def new
    @post = Post.new
    @post.user = current_user
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image, :profilephoto)
    end
end

app/controllers/userprofile_controller.rb
class UserprofileController < ApplicationController
	before_action :authenticate_user!, only: [:userprofile]
	def userprofile
		@posts = Post.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/userprofile_helper.rb
module UserprofileHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <br>
  <hr>
  <div id ="comments ">
    <div id = "comment-show" style = "float:left" class = "pull-left">
      <%= comment.body %>
    </div>
    <% if @post.user == current_user || comment.user == current_user%> 
      <div id = "comment-show" style = "float:left" class = "pull-right">
      <%= link_to 'Delete', comment, method: :delete,  class: "deletebutton", remote: true %>
      </div>
    <% end %>
    <br>
    <div style = "float:left">
      <small>Posted by <%= comment.user.name %> <%= time_ago_in_words(comment.created_at) %> ago.</small>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
 $('#comments-list').append("<%= j render @comment %>");
 $('#focus-area').val("");
 $('#focus-area').focus();
var commentcount = <%= @post.comments.count %>;
$(".badge").text(parseInt(commentcount));

app/views/comments/destroy.js.erb
$("div#<%= dom_id(@comment)%>").hide();
var commentcount = <%= @post.comments.count %>;
$(".badge").text(parseInt(commentcount));

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstantShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if notice %>
	<div id = "notice">
		<p class="notice"><%= notice %></p>
	</div>
	<% elsif alert %>
	<div id = "notice">
    	<p class="alert"><%= alert %></p>
	</div>
	<% end %>
<nav class="navbar navbar-default navbar-fixed-top" style = "border-bottom-color:#ff5f2e;border-bottom-width:thick">
  <div class="container-fluid">
    <div class="navbar-header">
      <a id = "logo" class="navbar-brand" href="/posts">InstantShare</a>
    </div>
    
    <ul class="nav navbar-nav" style = "float:right">

      <% if user_signed_in? %>
      <li><%= link_to 'New Post', new_post_path, id: "nav-text" %></li>
      <li><%= link_to "My Profile", userprofile_path, id: "nav-text" %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, id: "nav-text" %></li>
      <% else %>
      <li><%= link_to "Sign In", new_user_session_path, id: "nav-text"%></li>
      <li><%= link_to "Sign Up", new_user_registration_path, id: "nav-text"%></li>
      <% end %>

    </ul>
  </div>
</nav>
	

<%= yield %>
<script>
$(document).ready(function(){
	setTimeout(function(){
		$("#notice").fadeOut("slow",function(){
			$("this").remove();
		})
	},1000);
});
</script>
</body>
</html>

app/views/posts/_comment.html.erb
<%= div_for(post) do %>
<%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm", remote: true do %>
<span class = "glyphicon glyphicon-thumbs-up"></span>
Like
<span class = "showupvotes"><%= post.get_upvotes.size %></span>
<% end %>
      
<%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm", remote: true do %>
<span class = "glyphicon glyphicon-thumbs-down"></span>
Disike
<span class = "showdownvotes"><%= post.get_downvotes.size %></span>
<% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %> 
<div class= "container-fluid" style = "width: 100%;text-align:center;">
  <div class ="container-fluid" style = "margin:0 auto;">

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class = "container-fluid" style = "display:inline-block">
    <div class = "form-group">
    <div class="file_botton" style ="margin:auto">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
    <br>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %> 
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary"%>
    </div>
  </div>


  </div>
</div>
<% end %>

app/views/posts/downvote.js.erb
$("#<%= dom_id(@post) %> .showupvotes").text("<%= @post.get_upvotes.size %>")
$("#<%= dom_id(@post) %> .showdownvotes").text("<%= @post.get_downvotes.size %>")

app/views/posts/edit.html.erb
<div class = "container-fluid" style= "padding: 80px 0 0 0; text-align:center">
  <div class = "jumbotron">
    <div class = "panel panel-info" style = "display:inline-block; padding: 20px 20px 20px 20px">
			<h1>Editing Post</h1>
			</div>
			<%= render 'form' %>

			<%= link_to 'Show', @post, class: "btn btn-default" %> 
			<%= link_to 'Back', posts_path, class: "btn btn-default" %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class= "container-fluid" style = "text-align:center;padding: 80px 0 0 0">
  <div  class ="container-fluid" style= "display:inline-block;padding:20px 300px; background-color:#1f4e5f;border-radius:20px">
          <span style = "color:white"><%= form_tag posts_path, :method => 'get' do %> <%= @posts.count %> posts</span>
          <span style = "color:black">
          <div class = "form-group form-inline">
          <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control" ,style: "float: left" %>
          <%= submit_tag "Search", :name => nil, class: "btn", style: "background-color:#fcbe32;float: right" %></span>
          </div>
          <% end %>
  </div>
  <br>
    <% if @posts.count == 0 %>
  <h1>No result.</h1>
  <% end %>
  <br>

  <% @posts.each do |post| %>


  <div class ="container-fluid" style = "width:;margin: 0 auto;background-color:white;display:inline-block; box-shadow: 10px 10px 10px 10px #888888;border-radius:5px">



  <div class = "container-fluid" style = "display:inline-block">
    <div style="padding:10px">
    </div>
    <div style = "float:left;color:#79a8a9"><%= image_tag post.user.profilephoto.url(:thumb), class: "img-circle" %> <%= post.user.name %>
    </div>
    <% if post.updated_at == post.created_at %>
      <div style = "float:right;color:grey"><%= time_ago_in_words(post.created_at) %></div>
    <% else %>
      <div style = "float:right;color:grey">Edited <%= time_ago_in_words(post.updated_at) %></div>
    <% end %>

    <div style = "padding:30px">
    </div>

    <div style = "display:inline-block"><%= image_tag post.image.url(:medium), style: "height:400px;width:400px" %></div>
    <div style ="text-align:center;color:#1f4e5f"><h3><strong><%= link_to "#{post.title}", post %></strong></h3></div>
    <div class ="container-fluid" style = "">
      <%= render 'comment' , post: post %>

      <div class= "panel">
      <span class="glyphicons glyphicons-comments"></span>
      Comments
      <span class="badge"><%= post.comments.size %></span>
      </div>
      
    </div>
  </div>
  

  </div>
  <div style = "height:60px">
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class = "container-fluid" style= "padding: 80px 0 0 0; text-align:center">
  <div class = "jumbotron">
    <div class = "panel panel-info" style = "display:inline-block; padding: 20px 20px 20px 20px">
		<h1>New Post</h1>

		<%= render 'form' %>
		 <br>
		<%= link_to 'Back', posts_path, class: "btn btn-default" %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class= "container-fluid" style = "text-align:center;padding: 80px 0 0 0">
  <div class ="container-fluid" style = "width:;margin: 0 auto;background-color:white;display:inline-block; box-shadow: 10px 10px 10px 10px #888888;">



  <div class = "container-fluid" style = "display:inline-block;padding:0 0 30px 0">
    <div style = "padding:20px">
    </div>
    <div style = "float:left;color:#79a8a9"><%= image_tag @post.user.profilephoto.url(:thumb), class: "img-circle" %> <%= @post.user.name %></div>
    <% if @post.updated_at == @post.created_at %>
    <div style = "float:right;color:grey"><%= time_ago_in_words(@post.created_at) %></div>
    <% else %>
    <div style = "float:right;color:grey">Edited <%= time_ago_in_words(@post.updated_at) %></div>
    <% end %>
    <div style = "padding:30px">
    </div>
    <div style = "display:inline-block"><%= image_tag @post.image.url(:large) %></div>
    <div style ="text-align:center;color:#1f4e5f"><h2><strong><%= @post.title %></strong></h2></div>
    <div style ="text-align:center;color:#fcbe32"><h4><strong><%= @post.body %></strong></h3></div>
  </div>
  	<div style = "height:60px">
  		<div style = "float:left;width:auto;display:inline-block" id = "comment-button">
  			 <a href = "#" style = "text-decoration:none"><strong>Comments </strong></a><span class="badge" id = "commentcount"><%= @post.comments.count%></span>
  		</div>



  		<div>
  			<div id = "comments-list">
  				<%= render :partial => @post.comments %>
  			</div>
  			<br>
  			<div style = "height:20px">
  				
  			</div>
  			<div>
	  			<%= simple_form_for [@post, Comment.new], remote: true do |f| %>
	  				<%= f.text_area :body, class: "form-control focus-area", id: "focus-area" %>
	  				<br>
	  				<%= f.submit "Add comment", class: "btn btn-primary pull-right addcomment" , remote: true %>
	  				</br>
				<% end %>
			</div>

  		</div>

  	</div>

  </div>
  <div style = "padding: 30px">
  	<%= link_to 'Back', posts_path, class: "btn btn-default" %>
  	<% if @post.user == current_user %> 
		<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
		<%= link_to 'Delete', @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%>
	  <% end %>
   </div>

</div>
<script>
var n =0;
$(document).ready(function(){
	$("#comment-button").click(function(){
		event.preventDefault();
		$("#comments-list").fadeToggle(1000);
		$(".focus-area").focus();
    
	});

  $(".badge").text(<%= @post.comments.count%>);

	
});
</script>

app/views/posts/upvote.js.erb
$("#<%= dom_id(@post) %> .showupvotes").text("<%= @post.get_upvotes.size %>")
$("#<%= dom_id(@post) %> .showdownvotes").text("<%= @post.get_downvotes.size %>")

app/views/posts/userprofile.html.erb
  <% @posts.each do |post| %>


  <div class ="container-fluid" style = "width:;margin: 0 auto;background-color:white;display:inline-block; box-shadow: 10px 10px 10px 10px #888888;border-radius:5px">



  <div class = "container-fluid" style = "display:inline-block">
    <div style = "float:left;color:#79a8a9"><%= post.user.name %></div>
    <% if post.updated_at == post.created_at %>
    <div style = "float:right;color:grey"><%= time_ago_in_words(post.created_at) %></div>
    <% else %>
    <div style = "float:right;color:grey">Edited <%= time_ago_in_words(post.updated_at) %></div>
    <% end %>
    <div style = "display:inline-block"><%= image_tag post.image.url(:medium) %></div>
    <div style ="text-align:center;color:#1f4e5f"><h3><strong><%= link_to "#{post.title}", post %></strong></h3></div>
    <div class ="container-fluid" style = "">
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
      <span class = "glyphicon glyphicon-thumbs-up"></span>
      Like
      <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
      <span class = "glyphicon glyphicon-thumbs-down"></span>
      Disike
      <%= post.get_downvotes.size %>
      <% end %>

      <div class= "panel">
      <span class="glyphicons glyphicons-comments"></span>
      Comments
      <span class="badge"><%= post.comments.size %></span>
      </div>
      
    </div>
  </div>
  

  </div>
  <div style = "height:60px">
  </div>
  <% end %>

app/views/userprofile/userprofile.html.erb
<div class = "container-fluid" style= "padding: 80px 0 0 0; text-align:center;">
  <div class = "jumbotron">
    <div class = "panel panel-info" style = "display:inline-block; padding: 20px 20px 20px 20px;background-color:#1f4e5f">

      <%= image_tag current_user.profilephoto.url(:medium),class: "img-circle" %><h1><span style = "color:#fcbe32;"><%= current_user.name %></span></h1> 
      <br>
      <h2><span style = "color:#fcbe32;"><%= current_user.posts.count%> posts</h2> </span><%= link_to "Edit Account", edit_user_registration_path, id: "nav-text" %>
      <div class= "container-fluid" style = "padding:80px">
          <% @posts.each do |post| %>

          <% if post.user == current_user %>
          <div class ="container-fluid" style = "float:left;border-radius:5px;padding:30px;margin:20px;background-color:white">



            <div class = "container-fluid" style = "display:inline-block">
              <% if post.updated_at == post.created_at %>
              <div style = "float:right;color:grey"><%= time_ago_in_words(post.created_at) %></div>
              <% else %>

              <div style = "float:right;color:grey">Edited <%= time_ago_in_words(post.updated_at) %></div>
              <% end %>
              <br>
              <div style = "display:inline-block"><%= image_tag post.image.url(:thumb) %></div>
              <div style ="text-align:center;color:#1f4e5f"><h3><strong><%= link_to "#{post.title}", post %></strong></h3></div>
            
            </div>

          

          </div>
          <% end %>
          <%end %>
      </div>

    </div>
  </div>
</div>